### PR TITLE
Upgrade version to 18.2.0 for Next.js 13

### PR DESCRIPTION
**Pull request by maxproske**
Next.js 13 bumped the minimum React version from 17.0.2 to [18.2.0](https://nextjs.org/docs/upgrading).

x-ref: https://github.com/vercel/next.js/issues/42530

### CODE REVIEW

**Comment by maxproske** [comment]
@marvinhagemeister just in case notifications aren't sent. Cheers!

**Comment by maxproske** [comment]
@marvinhagemeister Hopefully I'm not creating extra pressure by asking when this PR will be reviewed.

**Comment by acapro** [comment]
I really need this as well, in the meantime I just published a forked version of this package to support React 18 peer dependancies: https://www.npmjs.com/package/preact-compat-alias-latest 🧪 (patch-package was not able to solve this either)

**Comment by daniel-rose** [comment]
What is the status of this ticket? Is there a date when the next release will come?

**Comment by FleetAdmiralJakob** [comment]
Hey, pls. bumb it to 18.2.0, cause I need this rly for my projects.

**Comment by is-jonreeves** [comment]
Any news on this getting merged?

**Comment by poof86** [comment]
Bumb it good bump it because we should?

**Comment by rschristian** [comment]
Preact does not match React v18 fully (and perhaps won't). The version here will not fall out of sync with [the version we ship in `preact/compat`](https://github.com/preactjs/preact/blob/cece8c3957c0f2200ec3df92c761f7529a9b5356/compat/src/index.js#L38).

We don't support using Preact w/ Next anymore anyhow; the Next team broke support rather often and then bought in completely to React. Eventually it became quite obvious that it was not a good use of our time to try to maintain support when they clearly did not care to keep it themselves.

I'm going to close this out as there's no plan to alter the React version compat masquerades as for now.

**Pull request closed without merging**
